NATS_HOST = 'localhost'
NATS_PORT = 4222
SMTP_HOST = 'smtp.gmail.com'
SMTP_PORT = 587
SMTP_USERNAME = 'aaa.fff'
SMTP_PASSWORD = 'xxx'
FROM_NAME = 'Halina from OCM'
FROM_EMAIL = 'test@test.com'
TELESCOPES = ['jk15','zb08']
EMAILS_TO = ['test2@test.com']
CHARTS_UTC_OFFSET_HOURS = 4
OBSERVATORY_TIMEZONE = -4
SEND_AT = 18
SEND_AT_MIN = 0